[build]
command = "source /opt/buildhome/.phpbrew/bashrc && phpbrew update && phpbrew known && phpbrew install 7.0.3 +default && phpbrew switch 7.03 && phpbrew app get composer && composer require tightenco/jigsaw && ./vendor/bin/jigsaw build"
publish = "/build_local"