[build]
command = "source /opt/buildhome/.phpbrew/bashrc && phpbrew install 7.0.3 +default && phpbrew switch 5.6.32 && phpbrew app get composer && composer require tightenco/jigsaw && ./vendor/bin/jigsaw build"
publish = "/build_local"